-- Run this entire file in the SQL Editor of your dedicated Supabase project.
-- Safe to rerun; does not delete existing gallery data.
begin;

create table if not exists public.categories (
  id integer generated by default as identity primary key,
  name text not null check (length(btrim(name)) between 1 and 60)
);
create unique index if not exists categories_name_unique on public.categories (lower(name));
create table if not exists public.media (
  id integer generated by default as identity primary key,
  title text not null check (length(btrim(title)) between 1 and 120),
  category_id integer not null references public.categories(id) on delete restrict,
  filename text not null unique,
  type text not null check (type in ('photo', 'video')),
  created_at timestamptz not null default now()
);
create index if not exists media_category on public.media(category_id);
create table if not exists public.sessions (
  token text primary key,
  expires bigint not null
);
create index if not exists sessions_expiry on public.sessions(expires);

-- Only the Node server's secret key can access these tables/functions.
alter table public.categories enable row level security;
alter table public.media enable row level security;
alter table public.sessions enable row level security;
revoke all on public.categories, public.media, public.sessions from anon, authenticated;
grant select, insert, update, delete on public.categories, public.media, public.sessions to service_role;
grant usage, select on sequence public.categories_id_seq, public.media_id_seq to service_role;

create or replace function public.gallery_categories()
returns table(id integer, name text, count bigint)
language sql stable security invoker set search_path = ''
as $$
  select c.id, c.name, count(m.id)
  from public.categories c left join public.media m on m.category_id = c.id
  group by c.id order by c.name;
$$;

create or replace function public.gallery_search(
  search_text text default '', category_filter integer default null,
  type_filter text default '', requested_page integer default 1
) returns jsonb
language plpgsql stable security invoker set search_path = ''
as $$
declare
  item_count integer;
  page_count integer;
  current_page integer;
  result_items jsonb;
begin
  -- strpos makes %, _, quotes and backslashes literal search characters.
  select count(*) into item_count
  from public.media m join public.categories c on c.id = m.category_id
  where (strpos(lower(m.title), lower(search_text)) > 0 or strpos(lower(c.name), lower(search_text)) > 0)
    and (category_filter is null or m.category_id = category_filter)
    and (type_filter = '' or m.type = type_filter);
  page_count := greatest(1, (item_count + 8) / 9);
  current_page := least(page_count, greatest(1, requested_page));
  select coalesce(jsonb_agg(to_jsonb(entry) order by entry.id desc), '[]'::jsonb) into result_items
  from (
    select m.*, c.name as category
    from public.media m join public.categories c on c.id = m.category_id
    where (strpos(lower(m.title), lower(search_text)) > 0 or strpos(lower(c.name), lower(search_text)) > 0)
      and (category_filter is null or m.category_id = category_filter)
      and (type_filter = '' or m.type = type_filter)
    order by m.id desc limit 9 offset (current_page - 1) * 9
  ) entry;
  return jsonb_build_object('items', result_items, 'total', item_count, 'page', current_page, 'pages', page_count);
end;
$$;
revoke all on function public.gallery_categories() from public, anon, authenticated;
revoke all on function public.gallery_search(text, integer, text, integer) from public, anon, authenticated;
grant execute on function public.gallery_categories() to service_role;
grant execute on function public.gallery_search(text, integer, text, integer) to service_role;

-- Public viewing only; uploads/deletes use the server secret key.
-- No anonymous or authenticated write policies are created.
insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values ('gallery', 'gallery', true, 50000000,
  array['image/jpeg','image/png','image/webp','video/mp4','video/webm'])
on conflict (id) do update set public = excluded.public,
  file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;
commit;
